name: Dynamic SCA Ignores

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.19'

    - name: Clone remote repository
      uses: actions/checkout@v3
      with:
        repository: samsnyk/dynamic-sca-ignores
        ref: main
        path: snyk-dynamic-sca-ignores
        token: ${{ secrets.DYNAMIC_SCA_REPO_TOKEN }}

    - name: Install dependencies
      run: |
        cd snyk-dynamic-sca-ignores
        python -m pip install --upgrade pip
        pip install -r requirements.txt
                
    - name: Run script from external repo
      run: |
        cd snyk-dynamic-sca-ignores
        pwd
        ls -la
        python main.py generate ${{github.workspace}}/snyk-dynamic-sca-ignores/templates/tenants ${{github.workspace}}/.snyk tenant-a group-a organization-a target-a
        
    - name: Cleanup external repository
      run: |
        rm -rf snyk-dynamic-sca-ignores
