name: Dynamic SCA Ignores

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Clone remote repository
      uses: actions/checkout@v3
      with:
        repository: samsnyk/dynamic-sca-ignores
        path: snyk-dynamic-sca-ignores
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run script from external repo
      run: |
        cd snyk-dynamic-sca-ignores
        python src/main.py generate_dot_snyk_file ../.snyk tenant-a group-a organization-a, target-a
        
    - name: Cleanup external repository
      run: |
        rm -rf snyk-dynamic-sca-ignores
